version: '3.8'

services:
  app:
    build: .
    container_name: node-app
    ports:
      - "3000:3000"
    volumes: 
      - .:/src/app
      - /src/app/node_modules
    depends_on:
      - mysqldb
    env_file:
    - .env
  mysqldb:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      # Expose the MySQL port
      - "3307:3306"
    volumes:
      # mount the init into the containers init folder
      - ./migrations/init_migrations.sql:/docker-entrypoint-initdb.d/init.sql
      # persist the database data 
      - db-data:/var/lib/mysql

volumes:
  db-data:
