version: '3.8'

services:
  app:
    build: .
    container_name: node-app
    ports:
      - "3000:3000"
    depends_on:
      - mysqldb
    env_file:
    - .env
  mysqldb:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_MIGRATION_PASSWORD}
      MYSQL_DATABASE: ${DB_MIGRATION_NAME}
    ports:
      # Expose the MySQL port
      - "${DB_MIGRATION_PORT:-3307}:3306"
    volumes:
      # mount the init into the containers init folder
      - ./database/init_migrations.sql:/docker-entrypoint-initdb.d/init.sql
      # persist the database data 
      - db-data:/var/lib/mysql

volumes:
  db-data:
